# Generated by Django 3.2 on 2021-06-08 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('openId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nickName', models.CharField(max_length=100, null=True)),
                ('gender', models.SmallIntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0)),
                ('country', models.CharField(max_length=30, null=True)),
                ('province', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('rewardPoints', models.IntegerField(default=0)),
                ('stepNumbers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineName', models.CharField(max_length=50)),
                ('instruction', models.CharField(max_length=30)),
                ('times', models.CharField(max_length=30)),
                ('remark', models.CharField(max_length=1000, null=True)),
                ('openId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.userinfo')),
            ],
            options={
                'unique_together': {('openId', 'medicineName')},
            },
        ),
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')])),
                ('telephone', models.CharField(max_length=11)),
                ('province', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=False)),
                ('openId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.userinfo')),
            ],
            options={
                'unique_together': {('openId', 'name', 'gender', 'telephone', 'province', 'city', 'district', 'detail')},
            },
        ),
    ]
